ISSUE-15 Asking for confirmation before import command is executed
WeareJH/stripped-db-provider pull request #19
Opened 2024-01-12 16:34 UTC by bartoszkubicki

2024-01-12 20:04 UTC, maciejslawik requested changes

2024-01-12 20:04 UTC, maciejslawik commented on src/Console/ImportFromRemoteCommand.php
> +            'Are you sure you want to import database from S3? It will override curren environment database',
`curren` - typo

2024-01-15 07:57 UTC, bartoszkubicki commented on src/Console/ImportFromRemoteCommand.php
> +            'Are you sure you want to import database from S3? It will override curren environment database',
Fixed

2024-01-15 07:57 UTC, maciejslawik approved these changes

2024-01-15 08:32 UTC, merged